### ISSUE TITLE
Points of LinearRing do not form a closed linestring

### ISSUE THREAD

**Issue by xcmonline** [meteoinfo/MeteoInfo#26]
MeteoInfo-3.3.0

对已绘制的layer进行按行政边界裁剪（layer.clip）当图例中的values最小值设置超一定范围报异常，设置适当的值则裁剪正常，裁剪会受到图例的值范围影响。

java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring

	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:90)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:85)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:382)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:369)
	at org.meteoinfo.geometry.shape.Polygon.toGeometry(Polygon.java:240)
	at org.meteoinfo.geometry.shape.PolygonShape.toGeometry(PolygonShape.java:162)
	at org.meteoinfo.geometry.shape.Shape.toGeometry(Shape.java:293)
	at org.meteoinfo.geometry.shape.Shape.intersection(Shape.java:327)
	at org.meteoinfo.geo.layer.VectorLayer.clip(VectorLayer.java:1651)
	at org.meteoinfo.geo.layer.VectorLayer.clip(VectorLayer.java:1629)
	at org.meteoinfo.geo.layer.VectorLayer.clip(VectorLayer.java:1607)

**Comment by Yaqiang** [comment]
Can you provide test code to reproduce the problem?

**Comment by xcmonline** [comment]
> Can you provide test code to reproduce the problem?

源文件与行政边界有发您邮箱(yaqiang.wang@gmail.com)。

**Comment by Yaqiang** [comment]
It's a bug and thanks for your report! It has been sovled in this PR: https://github.com/meteoinfo/MeteoInfo/commit/8627374c9ab195f3e75e1866ec424f8b62cc1365

**Comment by xcmonline** [comment]
如果再增加一个小的色阶值及颜色[3,5,7,9,11,13,15,17]还是会报 found non-noded intersection between LINESTRING 异常。
