### ISSUE TITLE
Failed to create MKL instance:

### ISSUE THREAD

**Issue by jarvisqi** [meteoinfo/MeteoInfo#33]
GridData gridData = GeoMathUtil.interpolateData(stationData, interpolationSetting);

5:14:04.801 [main] DEBUG smile.math.blas.LAPACK - Failed to create MKL instance: 
java.lang.ClassNotFoundException: smile.math.blas.mkl.MKL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at smile.math.blas.LAPACK.MKL(LAPACK.java:48)
	at smile.math.blas.LAPACK.getInstance(LAPACK.java:39)
	at smile.math.blas.LAPACK.<clinit>(LAPACK.java:35)
	at smile.math.matrix.Matrix.svd(Matrix.java:1573)
	at smile.interpolation.KrigingInterpolation2D.<init>(KrigingInterpolation2D.java:103)
	at org.meteoinfo.math.interpolate.InterpUtil.kriging(InterpUtil.java:963)
	at org.meteoinfo.geo.util.GeoMathUtil.interpolateData(GeoMathUtil.java:273)

dependencice:

    implementation 'org.meteothink:meteoinfo-common:3.5'  
    implementation 'org.meteothink:meteoinfo-math:3.5'  
    implementation 'org.meteothink:meteoinfo-data:3.5'  
    implementation 'org.meteothink:meteoinfo-geo:3.5'
    implementation 'org.meteothink:meteoinfo-geometry:3.5'
    implementation 'org.meteothink:meteoinfo-projection:3.5'
    implementation 'org.meteothink:meteoinfo-ndarray:3.5'
    implementation 'org.meteothink:meteoinfo-image:3.5'
    implementation 'org.meteothink:meteoinfo-dataframe:3.5'
    implementation 'org.meteothink:meteoinfo-table:3.5'

OS：Windows11
JDK:1.8 、IDEA

**Comment by Yaqiang** [comment]
If MKL is not avaliable, OpenBLAS will be used.

**Comment by jarvisqi** [comment]
> If MKL is not avaliable, OpenBLAS will be used.

thanks ！
Reference required：
   ` implementation 'com.github.haifengl:smile-mkl:2.6.0'`
